// episodes-data.js
// Base de dados curada dos melhores episódios para viralizar
// Critérios: memes conhecidos, cenas icônicas, nostalgia alta, engajamento comprovado

module.exports = [
  // ─── BOB ESPONJA ───────────────────────────────────────────────────────────
  {
    show: "Bob Esponja",
    season: 1,
    episode: 1,
    title: "Help Wanted / Reef Blower / Tea at the Treedome",
    viralScore: 9,
    reason: "Episódio piloto — primeira aparição de todos os personagens. 'Eu estou pronto!' virou meme eterno.",
    memes: ["I'm ready!", "primeira aparição do Patrick", "Sandy estreia"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Bob Esponja",
    season: 1,
    episode: 6,
    title: "Mermaid Man and Barnacle Boy",
    viralScore: 8,
    reason: "Introdução dos super-heróis favoritos do Bob. Cenas de fã que todo mundo lembra.",
    memes: ["EVIL!", "Mermaid Man gritando"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Bob Esponja",
    season: 2,
    episode: 15,
    title: "Graveyard Shift",
    viralScore: 10,
    reason: "Episódio de terror mais icônico da série. 'No-Name' virou lenda. Alta nostalgia.",
    memes: ["Nosferatu acenando", "plantão da madrugada", "susto final"],
    platform: "Disney+",
    duration: 11,
  },
  {
    show: "Bob Esponja",
    season: 2,
    episode: 16,
    title: "Krusty Love",
    viralScore: 9,
    reason: "Sr. Siriguejo apaixonado. Bob xingando em bip. Uma das cenas mais engraçadas da série.",
    memes: ["Bob xingando censurado", "Sr. Siriguejo romântico"],
    platform: "Disney+",
    duration: 11,
  },
  {
    show: "Bob Esponja",
    season: 3,
    episode: 1,
    title: "The Algae's Always Greener / SpongeGard",
    viralScore: 9,
    reason: "Plankton troca de vida com o Sr. Siriguejo. Cenas absurdas e muito engraçadas.",
    memes: ["Plankton como gerente", "inversão de papéis"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Bob Esponja",
    season: 3,
    episode: 6,
    title: "Rock-a-Bye Bivalve",
    viralScore: 8,
    reason: "Bob e Patrick criam um filho. Patrick não trabalha. Clássico absoluto.",
    memes: ["Patrick preguiçoso", "família disfuncional"],
    platform: "Disney+",
    duration: 11,
  },

  // ─── SIMPSONS ──────────────────────────────────────────────────────────────
  {
    show: "Simpsons",
    season: 4,
    episode: 12,
    title: "Marge vs. the Monorail",
    viralScore: 10,
    reason: "Considerado o melhor episódio de todos. Monorail virou meme global. Escrito por Conan O'Brien.",
    memes: ["Monorail song", "Lyle Lanley", "Homer pilotando"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Simpsons",
    season: 5,
    episode: 2,
    title: "Cape Feare",
    viralScore: 10,
    reason: "Sideshow Bob pisando em ancinho repetidamente. Um dos momentos mais virais da TV.",
    memes: ["Bob pisando em ancinho", "rake scene"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Simpsons",
    season: 6,
    episode: 6,
    title: "Treehouse of Horror V",
    viralScore: 10,
    reason: "The Shinning — paródia de O Iluminado. 'No TV and no beer make Homer something something'.",
    memes: ["Homer no TV no beer", "Here's Johnny Homer", "Bart no futuro"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Simpsons",
    season: 7,
    episode: 10,
    title: "The Simpsons 138th Episode Spectacular",
    viralScore: 8,
    reason: "Compilação dos melhores momentos. Perfeito para clipes — cada cena é um highlight.",
    memes: ["múltiplos memes clássicos"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Simpsons",
    season: 8,
    episode: 2,
    title: "You Only Move Twice",
    viralScore: 10,
    reason: "Hank Scorpio — o melhor vilão da série. Homer quase salva o mundo sem perceber.",
    memes: ["Hank Scorpio", "Homer feliz trabalhando", "flamethrower"],
    platform: "Disney+",
    duration: 22,
  },
  {
    show: "Simpsons",
    season: 9,
    episode: 5,
    title: "The Cartridge Family",
    viralScore: 8,
    reason: "Homer compra uma arma. Cenas absurdas e muito engraçadas sobre cultura americana.",
    memes: ["Homer com arma", "NRA meeting"],
    platform: "Disney+",
    duration: 22,
  },

  // ─── DEXTER'S LABORATORY ───────────────────────────────────────────────────
  {
    show: "Dexter's Laboratory",
    season: 1,
    episode: 1,
    title: "The Big Cheese / EEK! A Mouse!",
    viralScore: 8,
    reason: "Episódio piloto. Dexter aprende francês dormindo. 'Omelette du fromage' virou meme.",
    memes: ["Omelette du fromage", "Dexter falando só francês"],
    platform: "HBO Max",
    duration: 11,
  },
  {
    show: "Dexter's Laboratory",
    season: 2,
    episode: 1,
    title: "Dexter Dodgeball / Dexter's Assistant",
    viralScore: 9,
    reason: "Dee Dee destruindo o laboratório de formas cada vez mais criativas. Clássico absoluto.",
    memes: ["Dee Dee destruindo tudo", "Dexter furioso"],
    platform: "HBO Max",
    duration: 11,
  },
  {
    show: "Dexter's Laboratory",
    season: 2,
    episode: 13,
    title: "Dexter's Rival",
    viralScore: 8,
    reason: "Mandark aparece como rival. Rivalidade épica entre os dois gênios.",
    memes: ["Mandark rindo", "rivalidade de gênios"],
    platform: "HBO Max",
    duration: 11,
  },

  // ─── DRAGON BALL Z ─────────────────────────────────────────────────────────
  {
    show: "Dragon Ball Z",
    season: 1,
    episode: 1,
    title: "The New Threat",
    viralScore: 8,
    reason: "Chegada de Raditz. Revelação que Goku é saiyajin. Momento que mudou tudo.",
    memes: ["Goku é um saiyajin", "Raditz chegando", "revelação épica"],
    platform: "Crunchyroll",
    duration: 22,
  },
  {
    show: "Dragon Ball Z",
    season: 3,
    episode: 21,
    title: "Transformed at Last",
    viralScore: 10,
    reason: "Goku vira Super Saiyajin pela primeira vez. Cena mais icônica do anime. Viraliza sempre.",
    memes: ["Goku SSJ", "cabelo dourado", "Frieza tremendo"],
    platform: "Crunchyroll",
    duration: 22,
  },
  {
    show: "Dragon Ball Z",
    season: 4,
    episode: 10,
    title: "Gohan's Rage",
    viralScore: 9,
    reason: "Gohan vira SSJ2 contra Cell. Cena épica com raio e transformação.",
    memes: ["Gohan SSJ2", "Cell com medo", "transformação épica"],
    platform: "Crunchyroll",
    duration: 22,
  },

  // ─── RICK AND MORTY ────────────────────────────────────────────────────────
  {
    show: "Rick and Morty",
    season: 1,
    episode: 1,
    title: "Pilot",
    viralScore: 9,
    reason: "Apresentação dos personagens. Rick bêbado com bomba. Tom imediato.",
    memes: ["Rick bêbado", "Morty assustado", "portal gun"],
    platform: "HBO Max",
    duration: 22,
  },
  {
    show: "Rick and Morty",
    season: 1,
    episode: 6,
    title: "Rick Potion #9",
    viralScore: 10,
    reason: "Morty destrói o mundo com poção de amor. Rick e Morty fogem para universo paralelo. Cena final devastadora.",
    memes: ["Cronenberg world", "cena final do jardim", "existencialismo"],
    platform: "HBO Max",
    duration: 22,
  },
  {
    show: "Rick and Morty",
    season: 2,
    episode: 1,
    title: "A Rickle in Time",
    viralScore: 9,
    reason: "Tempo dividido em múltiplas realidades. Visualmente insano. Rick quase morre.",
    memes: ["tempo dividido", "Rick sacrifício falso"],
    platform: "HBO Max",
    duration: 22,
  },
  {
    show: "Rick and Morty",
    season: 3,
    episode: 1,
    title: "The Rickshank Rickdemption",
    viralScore: 10,
    reason: "Rick escapa da prisão galáctica. Monólogo do szechuan sauce. Virou meme mundial.",
    memes: ["szechuan sauce", "Rick manipulando todos", "fuga épica"],
    platform: "HBO Max",
    duration: 22,
  },
];
